export const RecipesList = [
    {
      percent: "20%",
      image: "/assets/recipe1.jpeg",
      imageAlt: "Delicious Recipe 1",
      name: "Recipe 1",
      ingredients: "Ingredients for Recipe 1",
      time: "30 mins",
      rating: "4.5",
      vote: "100",
    },
    {
      percent: "15%",
      image: "/assets/recipe2.jpeg",
      imageAlt: "Delicious Recipe 2",
      name: "Recipe 2",
      ingredients: "Ingredients for Recipe 2",
      time: "45 mins",
      rating: "4.7",
      vote: "150",
    },

    {
      percent: "10%",
      image: "/assets/recipe3.jpeg",
      imageAlt: "Delicious Recipe 3",
      name: "Recipe 3",
      ingredients: "Ingredients for Recipe 3",
      time: "60 mins",
      rating: "4.9",
      vote: "200",
    },
    {
      percent: "25%",
      image: "/assets/recipe4.jpeg",
      imageAlt: "Delicious Recipe 4",
      name: "Recipe 4",
      ingredients: "Ingredients for Recipe 4",
      time: "40 mins",
      rating: "4.3",
      vote: "120",
    },
    {
      percent: "30%",
      image: "/assets/recipe5.jpeg",
      imageAlt: "Delicious Recipe 5",
      name: "Recipe 5",
      ingredients: "Ingredients for Recipe 5",
      time: "50 mins",
      rating: "4.8",
      vote: "180",
    },
    {
      percent: "20%",
      image: "/assets/recipe6.jpeg",
      imageAlt: "Delicious Recipe 6",
      name: "Recipe 6",
      ingredients: "Ingredients for Recipe 6",
      time: "35 mins",
      rating: "4.6",
      vote: "130",
    },
    {
      percent: "15%",
      image: "/assets/recipe7.jpeg",
      imageAlt: "Delicious Recipe 7",
      name: "Recipe 7",
      ingredients: "Ingredients for Recipe 7",
      time: "55 mins",
      rating: "4.4",
      vote: "140",
    },
    {
      percent: "10%",
      image: "/assets/recipe8.jpeg",
      imageAlt: "Delicious Recipe 8",
      name: "Recipe 8",
      ingredients: "Ingredients for Recipe 8",
      time: "25 mins",
      rating: "4.2",
      vote: "110",
    },
  ];